language: node_js
install:
    - npm install -g truffle
    - npm install -g solc@0.4.21
    - npm install solidity-coverage
    - npm install ethereumjs-testrpc-sc
    - npm install codecov
script:
    - ls ./node_modules/.bin
    - ls ./node_modules/
    - npm run coverage
after_success:
    - codecov

