language: node_js
node_js:
  - "8"
install:
    - npm install -g truffle
    - npm install -g solc
    - npm install solidity-coverage
    - npm install ethereumjs-testrpc-sc
    - npm install codecov
script:
    - ls ./node_modules/.bin
    - ls ./node_modules/
    - npm run coverage
after_success:
    - codecov

